Add CI action for example branches
saleor/saleor-app-template pull request #143
Opened 2022-12-12 14:38 UTC by krzysztofwolski

2022-12-12 16:45 UTC, lkostrowski approved these changes

2022-12-12 18:30 UTC, NyanKiyoshi requested changes

2022-12-12 18:30 UTC, NyanKiyoshi commented on .github/workflows/manage-example-branches.yml
> +      - uses: actions-ecosystem/action-add-labels@v1
Make the action immutable
```suggestion
      - uses: actions-ecosystem/action-add-labels@bd52874380e3909a1ac983768df6976535ece7f8  # v1.1.0
```

2022-12-13 09:05 UTC, NyanKiyoshi approved these changes

2022-12-13 09:09 UTC, merged