Documentation improvements
saleor/saleor-app-template pull request #175
Opened 2023-07-04 11:34 UTC by peelar

## Context
We received feedback from @aniav about the difficulties in making the first steps with apps. This PR is one of the attempts to improve it.

## Features
- Linguistic fixes to the `README.md`.
- Added some extra content to the template's introductory page. It now includes instructions on installing the app in the dashboard, links to Next.js documentation, and the "tunneling the apps" article. Some small fixes with it as well.

## Screenshot

![image](https://github.com/saleor/saleor-app-template/assets/44495184/c175a727-5f07-46c0-b80d-7b502cd4dbfd)

2023-07-04 15:44 UTC, aniav reviewed
👌

2023-07-04 16:14 UTC, krzysztofwolski approved these changes

2023-07-05 06:27 UTC, lkostrowski requested changes

2023-07-05 06:27 UTC, lkostrowski commented on src/pages/index.tsx
> +          <code>graphql</code> - the pre-defined GraphQL queries.
maybe lets mark it more as a directory. `/graphql` or a simple icon. Other paths the same

2023-07-05 06:27 UTC, lkostrowski commented on src/pages/index.tsx
> +                    href="https://docs.saleor.io/docs/3.x/developer/extending/apps/developing-with-tunnels"
we have now 2 ways of doing it. Maybe lets give here 2 "paths" - with tunnels and locally. Just link two article to chose from

2023-07-05 06:27 UTC, lkostrowski commented on src/pages/index.tsx
> +                To install the app in your Saleor Dashboard, follow these steps:
It doesnt fit well if below we have this `<form>`. I mean its a different of doing the same field.

So if we give manual steps of installation, ensure its `.... OR ....`

2023-07-05 06:27 UTC, lkostrowski commented on src/pages/index.tsx
> +                    href="https://docs.saleor.io/docs/3.x/developer/extending/apps/developing-with-tunnels"
Im also not sure if these steps are required.

The form below is basically doing the same thing but automatically, under the hood. 

IMO its just complicating things.

Learn about tunneling or local development - needed
Explain steps on dashboard - not needed

2023-07-05 09:18 UTC, peelar commented
@lkostrowski addressed

2023-07-06 08:36 UTC, lkostrowski approved these changes

2023-07-06 09:50 UTC, merged